// Interface-only state. No network requests, credential storage, or script execution.
const advancedState={storeTab:'订阅',resourceTab:'代理集合',logLevel:'全部',paused:false,backups:['今天 09:30','昨天 22:18'],connections:['api.github.com','www.youtube.com','dns.alidns.com'],toggles:{},options:{},drafts:{},storeItems:['云端订阅','备用订阅'],storeGroups:['日常组合'],storeFiles:[Brand.nameEn.toLowerCase()+'.yaml'],overrides:['日常分流.yaml','节点整理.js'],davReady:false};
const catalog=[['substore','Sub-Store','订阅转换 · 合并 · 处理','sub'],['webdav','WebDAV','云端备份 · 跨设备恢复','cloud'],['rules','规则管理','匹配顺序与分流去向','rules'],['overrides','配置覆写','YAML / JavaScript','code'],['resources','外部资源','代理集合与规则集合','layers'],['connections','连接管理','实时请求与代理链路','connections'],['logs','运行日志','筛选、暂停与诊断','logs'],['core','内核设置','Mihomo · Smart Core','core']];
const groups={core:['内核设置',[['内核','Mihomo','Mihomo|Smart Core'],['Smart 规则覆写',false],['LightGBM 模型',false],['本地性能数据收集',false],['Smart 策略','粘性会话','粘性会话|轮询'],['DNS 设置','', 'route:dns'],['TUN 设置','', 'route:tun'],['端口与外部控制','', 'route:ports'],['高级配置','', 'route:advancedcore']]],dns:['DNS 设置',[['启用 DNS',true],['增强模式','Fake-IP','Fake-IP|Redir-Host'],['IPv6 解析',false],['遵循分流规则',true],['Nameserver','https://dns.alidns.com/dns-query','text'],['Fallback','https://1.1.1.1/dns-query','text'],['Fake-IP 过滤','*.lan, localhost','text'],['Nameserver Policy','按域名指定 DNS','text']]],tun:['TUN / VPN',[['VPN 服务',true],['协议栈','Mixed','Mixed|System|gVisor'],['自动路由',true],['严格路由',false],['DNS 劫持','any:53','text'],['MTU','1500','text'],['路由排除','192.168.0.0/16','text'],['应用分流','','route:apps']]],ports:['端口与外部控制',[['混合端口','7890','text'],['HTTP 端口','7891','text'],['SOCKS 端口','7892','text'],['允许局域网连接',false],['监听地址','127.0.0.1','text'],['外部控制器','127.0.0.1:9090','text'],['控制器密钥','未设置','text'],['外部面板','本地面板','text']]],advancedcore:['高级配置',[['IPv6',false],['域名嗅探',true],['统一延迟',true],['TCP 并发',true],['进程匹配','strict','strict|always|off'],['日志等级','info','debug|info|warning|error|silent'],['Geodata 加载','标准','标准|内存优化'],['Geo 数据更新周期','24 小时','24 小时|48 小时|手动']]],apps:['应用分流',[['分流模式','所有应用','所有应用|仅选定应用|排除选定应用'],['Chrome',true],['YouTube',true],['Telegram',true],['微信',false],['支付宝',false]]],android:['Android 集成',[['开机自动连接',false],['快捷设置磁贴',true],['常驻通知',true],['电池优化','未配置','查看设计'],['始终开启 VPN','系统设置','查看设计'],['断线阻断','系统设置','查看设计'],['Wi-Fi 自动连接',false]]],appearance:['外观与体验',[['主题色','Gemini','Gemini|Dracula|海盐'],['语言','简体中文','简体中文|English'],['节点布局','卡片','卡片|列表'],['首页快捷入口',true],['测速超时','5000 ms','text'],['测速地址','https://www.gstatic.com/generate_204','text']]]};
const parents={substore:'tools',webdav:'tools',rules:'tools',overrides:'tools',resources:'tools',connections:'tools',logs:'tools',core:'tools',dns:'core',tun:'core',ports:'core',advancedcore:'core',apps:'settings',android:'settings',appearance:'settings',config:'sub'};
const row=(id,title,desc='',symbol='settings')=>`<button class="setting-row" data-page="${id}">${icon(symbol)}<b>${title}</b><small>${desc}</small><span class="chevron">${icon('chevron')}</span></button>`;
const advHeader=(title,action='')=>`<div class="subheading"><button data-page="${parents[page]||'tools'}" aria-label="返回">${icon('back')}</button><h2>${title}</h2>${action}</div><div class="demo-caption">交互预览 · 数据与操作均为模拟</div>`;
const pill=(text,action)=>`<button class="primary" data-action="${action}">${text}</button>`;
const formField=(name,label,value='',type='text')=>`<label class="form-field">${label}<input name="${name}" type="${type}" value="${escapeText(value).replaceAll('"','&quot;')}" autocomplete="off" ${type==='url'?'placeholder="https://example.com"':''}></label>`;
const tabstrip=(items,current,key)=>`<div class="segmented advanced-tabs">${items.map(x=>`<button data-tab="${key}" data-value="${x}" class="${current===x?'active':''}">${x}</button>`).join('')}</div>`;
function goAdvanced(id){page=id;render();$('#screen').scrollTop=0}
function renderGroup(id){const [title,fields]=groups[id];return advHeader(title)+`<div class="card settings-card">${fields.map(([label,value,choices],i)=>{const key=id+':'+i;const v=advancedState.options[key]??value;if(typeof value==='boolean'){const on=advancedState.toggles[key]??value;return `<button class="setting-row" data-toggle="${key}" role="switch" aria-checked="${on}"><b>${label}</b><span class="switch ${on?'on':''}"></span></button>`}return `<button class="setting-row" data-option="${key}"><b>${label}</b><small>${escapeText(v)}</small><span class="chevron">${icon('chevron')}</span></button>`}).join('')}</div>`+(id==='core'?`<div class="action-row">${pill('重启内核','restart-core')}${pill('检查更新','core-update')}</div>`:'')+`<p class="note">设置仅保留在本次页面预览中，尚未应用到系统或代理内核。</p>`}
function renderAdvanced(){
 if(page==='appearance'&&window.Theme)return window.Theme.renderPage();
 if(page==='tools')return heading('工具箱','<span class="badge">WORKSPACE</span>')+'<p class="tool-intro">从订阅整理到云端备份，<br>把网络配置打理得井井有条。</p>'+`<div class="feature-grid">${catalog.map(([id,title,desc,symbol],i)=>`<button class="feature-card ${i<2?'featured':''}" data-page="${id}"><span class="feature-icon">${icon(symbol)}</span><span class="feature-arrow">${icon('arrow')}</span><b>${title}</b><small>${desc}</small></button>`).join('')}</div><p class="note">高级能力，按需使用。</p>`;
 if(groups[page])return renderGroup(page);
 if(page==='settings')return heading('偏好设置','<small>你的 '+Brand.html+'，由你定义</small>')+sections('连接与内核')+`<div class="card settings-card">${row('core','内核设置','Mihomo / Smart','settings')}${row('tun','TUN / VPN','路由与协议栈','shield')}${row('apps','应用分流','所有应用','proxy')}${row('android','Android 集成','通知与后台','home')}</div>`+sections('数据与服务')+`<div class="card settings-card">${row('webdav','WebDAV 备份','备份与恢复','cloud')}${row('substore','Sub-Store','订阅工作台','sub')}</div>`+sections('外观与更多')+`<div class="card settings-card"><button class="setting-row" id="setting-theme">${icon('settings')}<b>深色模式</b><span class="switch ${dark?'on':''}"></span></button>${row('appearance','主题与外观',window.Theme?window.Theme.label():'Gemini','moon')}${row('logs','运行日志','','clock')}<button class="setting-row" data-action="about"><b>关于 ${Brand.html}</b><small>设计预览 0.2</small><span class="chevron">${icon('chevron')}</span></button></div>`;
 if(page==='webdav')return advHeader('WebDAV 备份', '<span class="badge">云端同步</span>')+`<div class="backup-hero">${icon('cloud')}<div><b>让配置，随你同行。</b><p>订阅、覆写与偏好，一起备份。</p></div></div><div class="card settings-card">${row('webdav','服务器配置',advancedState.davReady?'已配置 · 演示':'未配置','cloud').replace('data-page="webdav"','data-action="dav-config"')}<button class="setting-row" data-toggle="auto-backup" role="switch" aria-checked="${!!advancedState.toggles['auto-backup']}"><b>自动备份</b><small>每日 · 仅 Wi-Fi</small><span class="switch ${advancedState.toggles['auto-backup']?'on':''}"></span></button></div><div class="action-row">${pill('↑ 立即备份','backup')}${pill('↓ 恢复备份','restore-latest')}</div>`+sections('备份历史','<span class="badge">示例记录</span>')+`<div class="card settings-card">${advancedState.backups.map((x,i)=>`<button class="setting-row" data-restore="${i}">${icon('sub')}<b>${x}<small class="row-sub">Pixel 9 · 订阅 / 覆写 / 偏好</small></b><small>128 KB</small><span class="chevron">${icon('chevron')}</span></button>`).join('')}</div><p class="note">恢复前可选择要还原的内容。<br>演示不会连接 WebDAV 服务器或上传配置。</p>`;
 if(page==='substore'){const s=advancedState;return advHeader('Sub-Store','<button class="mini-button" data-action="store-config">服务设置</button>')+`<div class="service-banner"><span class="feature-icon">${icon('sub')}</span><div><b>订阅工作台</b><small>整理、合并，生成适合你的订阅。</small></div><span class="badge">演示</span></div>`+tabstrip(['订阅','组合','文件'],s.storeTab,'storeTab')+`<div class="section-label">${s.storeTab==='订阅'?'我的订阅':s.storeTab==='组合'?'组合订阅':'托管文件'}<button data-action="store-add">＋ 新建</button></div>`+`<div class="card settings-card">${(s.storeTab==='订阅'?s.storeItems:s.storeTab==='组合'?s.storeGroups:s.storeFiles).map((x,i)=>`<button class="setting-row" data-store="${i}">${icon(s.storeTab==='组合'?'proxy':'sub')}<b>${escapeText(x)}<small class="row-sub">${s.storeTab==='订阅'?'6 个节点 · 2 个处理步骤':s.storeTab==='组合'?'云端订阅 + 备用订阅':'YAML · 生成配置文件'}</small></b><span class="chevron">${icon('chevron')}</span></button>`).join('')}</div>`+sections('处理流水线')+`<div class="pipeline"><span>来源</span><i>→</i><span>筛选 / 重命名</span><i>→</i><span>输出</span></div><div class="card settings-card"><button class="setting-row" data-action="processors">${icon('proxy')}<b>节点处理器</b><small>筛选 · 排序 · 脚本</small><span class="chevron">${icon('chevron')}</span></button><button class="setting-row" data-action="convert">${icon('globe')}<b>预览与导出</b><small>Mihomo</small><span class="chevron">${icon('chevron')}</span></button></div><p class="note">内置与远程服务均纳入设计。<br>本原型展示流程，尚未启动 Sub-Store 服务。</p>`}
 if(page==='rules')return advHeader('规则管理',pill('＋ 新建','rule-add'))+'<input class="search" id="rule-search" aria-label="搜索规则" placeholder="搜索域名、规则类型或策略">'+sections('匹配顺序','<span class="badge">从上到下</span>')+`<div class="card settings-card" id="rule-list">${[['DOMAIN-SUFFIX','github.com','代理'],['DOMAIN-SUFFIX','cn','DIRECT'],['RULE-SET','reject','REJECT'],['GEOIP','CN','DIRECT'],['MATCH','所有其他请求','代理']].map(([type,value,target],i)=>`<button class="setting-row filter-row" data-rule="${i}"><span class="order-number">0${i+1}</span><b>${value}<small class="row-sub">${type}</small></b><span class="badge">${target}</span></button>`).join('')}</div><p class="note">自定义规则通过覆写保存，订阅更新后仍可保留。</p>`;
 if(page==='overrides')return advHeader('配置覆写',pill('＋ 添加','override-add'))+`<div class="info-panel"><b>配置更新，自定义不丢失。</b><p>选择全局生效，或只应用于指定订阅。</p></div>`+sections('我的覆写','<small>按列表顺序执行</small>')+`<div class="card settings-card">${advancedState.overrides.map((x,i)=>`<button class="setting-row" data-editor="${i}">${icon('sub')}<b>${escapeText(x)}<small class="row-sub">${advancedState.options['scope:'+i]||(i===0?'全局生效':'云端订阅')} · ${x.endsWith('.js')?'JavaScript':'YAML'}</small></b><span class="chevron">${icon('chevron')}</span></button>`).join('')}</div><div class="action-row">${pill('从链接导入','override-import')}${pill('本地文件','override-file')}</div><p class="note">支持 YAML 合并与 JavaScript 处理。<br>原型编辑器只保存文本，不执行脚本。</p>`;
 if(page==='resources')return advHeader('外部资源',pill('↻ 更新全部','resources-update'))+tabstrip(['代理集合','规则集合','Geo 数据'],advancedState.resourceTab,'resourceTab')+`<div class="card settings-card">${(advancedState.resourceTab==='代理集合'?['云端节点','备用节点']:advancedState.resourceTab==='规则集合'?['reject','proxy','direct']:['GeoIP.dat','GeoSite.dat','Country.mmdb','ASN.mmdb']).map(x=>`<button class="setting-row" data-resource="${x}">${icon('globe')}<b>${x}<small class="row-sub">HTTP · 24 小时更新 · 刚刚</small></b><span class="badge">已就绪</span></button>`).join('')}</div><p class="note">查看资源来源、更新时间与内容，或单独刷新资源。</p>`;
 if(page==='connections')return advHeader('连接管理',pill('断开全部','disconnect-all'))+`<div class="connection-summary"><div><b>${advancedState.connections.length}</b><small>活跃连接</small></div><div><b>12.8 <em>MB/s</em></b><small>下载速度</small></div></div><input class="search" id="connection-search" aria-label="搜索连接" placeholder="搜索域名、应用或链路">`+sections('当前连接','<small>演示快照</small>')+`<div class="card settings-card">${advancedState.connections.map((x,i)=>`<button class="setting-row filter-row" data-connection="${i}">${icon('globe')}<b>${x}<small class="row-sub">${i===2?'系统 · DIRECT':'Chrome · 代理 → 香港 01'}</small></b><small>TCP ›</small></button>`).join('')||'<p class="note">暂无活跃连接</p>'}</div>`;
 if(page==='logs')return advHeader('运行日志',pill(advancedState.paused?'继续':'暂停','log-pause'))+tabstrip(['全部','INFO','WARN','ERROR'],advancedState.logLevel,'logLevel')+'<input class="search" id="log-search" aria-label="搜索日志" placeholder="搜索日志内容">'+`<div class="log-list">${[['INFO','09:41:02','模拟连接建立 → 香港 01'],['INFO','09:41:01','配置载入完成 · 规则模式'],['WARN','09:40:59','示例：备用节点响应较慢'],['INFO','09:40:58','DNS 配置已载入']].filter(x=>advancedState.logLevel==='全部'||x[0]===advancedState.logLevel).map(([level,time,text])=>`<div class="log-item filter-row"><span class="badge">${level}</span><time>${time}</time><p>${text}</p></div>`).join('')||'<p class="empty">没有对应等级的日志</p>'}</div><p class="note">${advancedState.paused?'已暂停显示。':'当前为静态日志样例。'}</p>`;
 if(page==='config')return advHeader('配置文件',pill('保存草稿','config-save'))+`<label class="form-field">云端订阅 · YAML<textarea class="code-editor" id="config-code" spellcheck="false">${escapeText(advancedState.drafts.config||'mixed-port: 7890\nmode: rule\nlog-level: info\ndns:\n  enable: true\n  enhanced-mode: fake-ip\n# 演示配置') }</textarea></label><div class="card settings-card">${row('overrides','关联覆写','日常分流.yaml','sub')}</div><p class="note">编辑结果仅在本次预览保留，尚未进行 YAML 校验。</p>`;
 return null;
}
const originalRender=render;
render=function(){originalRender();const advanced=renderAdvanced();if(advanced!==null)$('#screen').innerHTML=advanced;const active=['home','proxy','sub','settings','tools'].includes(page)?page:page==='config'?'sub':['apps','android','appearance'].includes(page)?'settings':'tools';$('#nav').innerHTML=[['home','概览'],['proxy','代理'],['sub','订阅'],['tools','工具'],['settings','设置']].map(([id,t])=>`<button data-page="${id}" class="${active===id?'active':''}" ${active===id?'aria-current="page"':''}><span class="nav-icon">${icon(id)}</span>${t}</button>`).join('');if(page==='sub')$('#screen').insertAdjacentHTML('beforeend',sections('订阅工作台')+`<div class="card settings-card">${row('substore','Sub-Store','转换与合并','sub')}${row('config','编辑配置','YAML','sub')}${row('overrides','关联覆写','全局 / 当前订阅','proxy')}${row('webdav','备份与恢复','WebDAV','cloud')}</div>`);if(page==='proxy')$('#screen').insertAdjacentHTML('beforeend',`<div class="card settings-card">${row('core','Smart Core','智能选择','settings')}${row('rules','规则管理','匹配去向','shield')}${row('connections','连接管理','请求链路','globe')}</div>`);};
function showDavConfig(){sheet('WebDAV 服务器',`<p>配置表单预览，请使用演示信息。</p><form id="dav-form">${formField('url','服务器地址','https://dav.example.com','url')}${formField('username','用户名','demo')}${formField('password','应用密码','','password')}${formField('path','备份目录','/'+Brand.nameEn+'/backups')}<div class="action-row">${pill('测试连接','dav-test')}${pill('保存配置','dav-save')}</div></form>`)}
function showRestore(i){sheet('恢复备份',`<p>${escapeText(advancedState.backups[i]||'示例备份')} · 选择要恢复的内容</p><div class="check-list"><label><input type="checkbox" checked> 订阅与配置</label><label><input type="checkbox" checked> 覆写与规则</label><label><input type="checkbox" checked> 应用偏好</label><label><input type="checkbox"> Sub-Store 数据</label></div><p>本次只演示恢复流程。</p>${pill('恢复所选内容','restore-confirm')}`)}
function showEditor(i){const name=advancedState.overrides[i];sheet('编辑覆写',`<p>${escapeText(name)}</p><label class="form-field">生效范围<select id="override-scope"><option>全局</option><option>云端订阅</option><option>停用</option></select></label><label class="form-field">内容<textarea id="override-code" class="code-editor" spellcheck="false">${escapeText(advancedState.drafts[i]??(name.endsWith('.js')?'function main(config) {\n  return config;\n}':'+rules:\n  - DOMAIN-SUFFIX,example.com,DIRECT'))}</textarea></label><button class="primary" data-save-editor="${i}">保存草稿</button>`);$('#override-scope').value=advancedState.options['scope:'+i]||'全局'}
document.addEventListener('input',e=>{if(['rule-search','connection-search','log-search'].includes(e.target.id)){const q=e.target.value.toLowerCase();$('#screen').querySelectorAll('.filter-row').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(q))}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.tab){advancedState[b.dataset.tab]=b.dataset.value;render()}
 if(b.dataset.toggle){const k=b.dataset.toggle;const initial=k.includes(':')?groups[k.split(':')[0]][1][Number(k.split(':')[1])][1]:false;advancedState.toggles[k]=!(advancedState.toggles[k]??initial);render()}
 if(b.dataset.option){const key=b.dataset.option,[id,i]=key.split(':'),[label,value,choices]=groups[id][1][i];if(choices.startsWith('route:'))goAdvanced(choices.slice(6));else sheet(label,`<p>设置预览</p><label class="form-field">${label}${choices==='text'?`<input id="option-value" value="${escapeText(advancedState.options[key]??value).replaceAll('"','&quot;')}">`:`<select id="option-value">${choices.split('|').map(x=>`<option ${x===(advancedState.options[key]??value)?'selected':''}>${x}</option>`).join('')}</select>`}</label><button class="primary" data-save-option="${key}">保存选择</button>`)}
 if(b.dataset.saveOption){advancedState.options[b.dataset.saveOption]=$('#option-value').value;$('#modal').innerHTML='';render();toast('已保存到本次预览')}
 if(b.dataset.restore!==undefined)showRestore(Number(b.dataset.restore));
 if(b.dataset.editor!==undefined)showEditor(Number(b.dataset.editor));
 if(b.dataset.saveEditor!==undefined){advancedState.drafts[b.dataset.saveEditor]=$('#override-code').value;advancedState.options['scope:'+b.dataset.saveEditor]=$('#override-scope').value;$('#modal').innerHTML='';render();toast('草稿已保留 · 未执行脚本')}
 if(b.dataset.store!==undefined){const type=advancedState.storeTab;sheet(type==='订阅'?'编辑订阅':type==='组合'?'编辑组合':'文件管理',`${formField('store-title','名称',type==='订阅'?advancedState.storeItems[Number(b.dataset.store)]:type==='组合'?advancedState.storeGroups[Number(b.dataset.store)]:advancedState.storeFiles[Number(b.dataset.store)])}${type==='组合'?'<div class="check-list"><label><input type="checkbox" checked> 云端订阅</label><label><input type="checkbox" checked> 备用订阅</label></div>':formField('store-source','来源链接','https://example.com/subscription','url')}<div class="action-row">${pill('处理步骤','processors')}${pill('输出预览','convert')}</div><button class="primary" data-store-save="${b.dataset.store}">保存草稿</button>`)}
 if(b.dataset.storeSave!==undefined){const name=$('[name="store-title"]').value.trim();if(!name)return toast('请输入名称');(advancedState.storeTab==='订阅'?advancedState.storeItems:advancedState.storeTab==='组合'?advancedState.storeGroups:advancedState.storeFiles)[Number(b.dataset.storeSave)]=name;$('#modal').innerHTML='';render();toast('已保存预览草稿')}
 if(b.dataset.rule!==undefined)sheet('规则详情',`<p>匹配优先级：${Number(b.dataset.rule)+1}</p><p>${escapeText(b.textContent)}</p>${pill('通过覆写修改','rule-add')}`);
 if(b.dataset.resource)sheet('资源详情',`<p>${escapeText(b.dataset.resource)}</p><p>类型：${advancedState.resourceTab}<br>更新周期：24 小时<br>来源：https://example.com/resources</p><div class="action-row">${pill('更新资源','resource-update')}${pill('预览内容','resource-view')}</div>`);
 if(b.dataset.connection!==undefined){sheet('连接详情',`<p>${escapeText(advancedState.connections[Number(b.dataset.connection)])}</p><dl class="detail-list"><dt>协议</dt><dd>TCP / TLS</dd><dt>应用</dt><dd>Chrome · 演示</dd><dt>源地址</dt><dd>192.0.2.2:52134</dd><dt>匹配规则</dt><dd>DOMAIN-SUFFIX</dd><dt>代理链</dt><dd>代理 → 香港 01</dd><dt>下载 / 上传</dt><dd>2.4 MB / 128 KB</dd></dl><button class="primary" data-end-connection="${b.dataset.connection}">断开此连接</button>`)}
 if(b.dataset.endConnection!==undefined){advancedState.connections.splice(Number(b.dataset.endConnection),1);$('#modal').innerHTML='';render();toast('已移除演示连接')}
 if(!b.dataset.action)return;const action=b.dataset.action;
 switch(action){
 case'dav-config':showDavConfig();break;
 case'dav-test':case'dav-save':{const f=$('#dav-form');if(!/^https?:\/\/\S+$/.test(f.elements.url.value))return toast('请输入有效的服务器地址');if(action==='dav-save'){advancedState.davReady=true;$('#modal').innerHTML='';render()}toast(action==='dav-test'?'模拟测试通过 · 未连接服务器':'已模拟保存 · 凭据未存储');break}
 case'backup':if(!advancedState.davReady){showDavConfig();toast('先完成演示服务器配置');break}advancedState.backups.unshift('刚刚 · 演示备份');render();toast('已创建演示备份记录');break;
 case'restore-latest':showRestore(0);break;
 case'restore-confirm':if(!$('#modal input:checked'))return toast('至少选择一项内容');$('#modal').innerHTML='';toast('恢复流程演示完成 · 未更改真实配置');break;
 case'store-config':sheet('Sub-Store 服务',`<label class="form-field">运行方式<select><option>内置服务</option><option>远程服务</option></select></label>${formField('endpoint','远程服务地址','https://example.com/substore','url')}${formField('token','访问令牌','','password')}<p>真实服务接入将在功能开发阶段实现。</p>${pill('保存服务设置','store-config-save')}`);break;
 case'store-config-save':$('#modal').innerHTML='';toast('已模拟保存服务设置');break;
 case'store-add':sheet('新建'+advancedState.storeTab,`${formField('new-name','名称')}${formField('new-source','来源链接','https://example.com/subscription','url')}<p>保存后可继续编辑来源和处理步骤。</p>${pill('添加草稿','store-add-save')}`);break;
 case'store-add-save':{const n=$('[name="new-name"]').value.trim();if(!n)return toast('请输入名称');(advancedState.storeTab==='订阅'?advancedState.storeItems:advancedState.storeTab==='组合'?advancedState.storeGroups:advancedState.storeFiles).push(n);$('#modal').innerHTML='';render();break}
 case'processors':sheet('节点处理器','<p>按顺序处理来源节点。</p><div class="check-list"><label><input type="checkbox" checked> 地区 / 正则筛选</label><label><input type="checkbox" checked> 正则重命名</label><label><input type="checkbox"> 节点去重与排序</label><label><input type="checkbox"> 节点属性修改</label><label><input type="checkbox"> JavaScript 脚本处理</label></div>'+formField('filter','筛选表达式','香港|日本')+pill('预览输出','convert'));break;
 case'convert':sheet('输出预览','<label class="form-field">目标格式<select><option>Mihomo</option><option>Surge</option><option>sing-box</option><option>URI</option></select></label><div class="info-panel"><b>输出节点 · 示例 6 个</b><p>香港 01 · 香港 02 · 日本 01<br>新加坡 01 · 美国 01 · 台湾 01</p></div><p>原型尚未执行格式转换。</p>'+pill('加入 '+Brand.html+' 订阅','store-use'));break;
 case'store-use':added.push('Sub-Store · 演示输出');$('#modal').innerHTML='';goAdvanced('sub');toast('已添加输出卡片（演示）');break;
 case'override-add':case'override-import':case'override-file':sheet('添加覆写',`${formField('override-name','文件名','自定义规则.yaml')}${action==='override-import'?formField('override-url','来源链接','','url'):''}${action==='override-file'?'<p>本地文件选择待安卓文件访问接入。这里可先新建编辑草稿。</p>':''}${pill('新建编辑草稿','override-create')}`);break;
 case'override-create':{const name=$('[name="override-name"]').value.trim();if(!/\.(yaml|yml|js)$/.test(name))return toast('文件名请使用 .yaml、.yml 或 .js');advancedState.overrides.push(name);render();showEditor(advancedState.overrides.length-1);break}
 case'rule-add':$('#modal').innerHTML='';goAdvanced('overrides');showEditor(0);break;
 case'resources-update':case'resource-update':toast('已模拟更新资源');break;
 case'resource-view':sheet('资源内容','<pre class="code-preview"># 示例资源\npayload:\n  - DOMAIN-SUFFIX,example.com</pre>');break;
 case'disconnect-all':advancedState.connections=[];render();toast('演示连接已清空');break;
 case'log-pause':advancedState.paused=!advancedState.paused;render();break;
 case'config-save':advancedState.drafts.config=$('#config-code').value;toast('已保存配置草稿 · 尚未校验或应用');break;
 case'restart-core':toast('模拟内核重启完成');break;
 case'core-update':sheet('内核更新','<p>Mihomo / Smart Core</p><p>功能开发阶段接入版本检查、更新与回退。当前没有下载或更换内核。</p>');break;
 case'about':sheet('关于 '+Brand.name,'<p>Android 界面原型 0.2</p><p>目标覆盖 Clash Party 功能范围，并按 Android 平台调整交互。当前所有连接、服务与备份均为模拟。</p>');break;
 }
});
document.addEventListener('submit',e=>e.preventDefault());
$('.version span').textContent='03 / Gemini';
render();

