import 'dart:async';
import 'dart:io';

import 'package:bfclash/common/boot_guard.dart';
import 'package:bfclash/common/common.dart';
import 'package:bfclash/common/system_dns.dart';
import 'package:bfclash/core/core.dart';
import 'package:bfclash/database/database.dart';
import 'package:bfclash/enum/enum.dart';
import 'package:bfclash/models/models.dart';
import 'package:bfclash/plugins/app.dart';
import 'package:bfclash/plugins/service.dart';
import 'package:bfclash/providers/actions/system_exit.dart';
import 'package:bfclash/providers/providers.dart';
import 'package:bfclash/state.dart';
import 'package:material_ui/material_ui.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' show basename;
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:url_launcher/url_launcher.dart';

part 'actions/common.dart';
part 'actions/setup.dart';
part 'actions/backup.dart';
part 'actions/core.dart';
part 'actions/system.dart';
part 'actions/store.dart';
part 'actions/theme.dart';
part 'actions/proxies.dart';
part 'actions/profiles.dart';
part 'actions/geo_resource.dart';
part 'actions/updating.dart';
part 'generated/action.g.dart';
